export { createFakeBMapGl, default as fakeBMapGl } from './fake-bmapgl'
export {
  FakeEventTarget,
  FakeMap,
  FakeMarker,
  FakeInfoWindow,
  FakeIcon,
  FakeLabel,
  FakeShapeOverlay,
  FakeCircle,
  FakePolyline,
  FakePolygon,
  FakeContextMenu,
  FakeMenuItem,
  FakeControl,
  FakeZoomControl,
  FakeScaleControl,
  FakeDistrictLayer,
  FakePrism,
  FakeGroundOverlay,
  FakeBounds,
  createCallLog,
} from './fake-bmapgl'
export {
  LifecycleInspector,
  getLifecycleInspector,
  getFakeBMapGl,
  resetLifecycleState,
  registerRuntimeCounters,
} from './lifecycle-inspector'
export type { LifecycleSnapshot } from './lifecycle-inspector'
export {
  createFakeBMapV4,
  FakeV4Bounds,
  FakeV4Circle,
  FakeV4EventStats,
  FakeV4EventTarget,
  FakeV4InfoWindow,
  FakeV4Label,
  FakeV4Map,
  FakeV4MapTypeId,
  FakeV4Marker,
  FakeV4Overlay,
  FakeV4Pixel,
  FakeV4Point,
  FakeV4Polygon,
  FakeV4Polyline,
  FakeV4Size,
  FakeV4ViewAnimation,
} from './fake-bmap-v4'
export type {
  FakeBMapV4,
  FakeBMapV4Namespace,
  FakeV4AnimationOptions,
  FakeV4Interaction,
} from './fake-bmap-v4'
