export { createFakeBMapGl, default as fakeBMapGl } from './fake-bmapgl'
export {
  FakeEventTarget,
  FakeMap,
  FakeMarker,
  FakeInfoWindow,
  FakeIcon,
  FakeLabel,
  FakeShapeOverlay,
  FakeCircle,
  FakePolyline,
  FakePolygon,
  FakeContextMenu,
  FakeMenuItem,
  FakeControl,
  FakeZoomControl,
  FakeScaleControl,
  FakeDistrictLayer,
  FakePrism,
  FakeGroundOverlay,
  FakeBounds,
  createCallLog,
} from './fake-bmapgl'
export {
  LifecycleInspector,
  getLifecycleInspector,
  getFakeBMapGl,
  resetLifecycleState,
  registerRuntimeCounters,
} from './lifecycle-inspector'
export type { LifecycleSnapshot } from './lifecycle-inspector'
export {
  createFakeBMapV4,
  createFakeV4JsonpRegistry,
  FakeV4Autocomplete,
  FakeV4AutocompleteResult,
  FakeV4BezierCurve,
  FakeV4Bounds,
  FakeV4Boundary,
  FakeV4CallbackQueue,
  FakeV4Circle,
  FakeV4ClusterLayer,
  FakeV4ContextMenu,
  FakeV4Convertor,
  FakeV4CustomOverlay,
  FakeV4EventStats,
  FakeV4EventTarget,
  FakeV4FillLayer,
  FakeV4Geocoder,
  FakeV4Geolocation,
  FakeV4GroundOverlay,
  FakeV4Heatmap,
  FakeV4Icon,
  FakeV4InfoWindow,
  FakeV4Label,
  FakeV4LineLayer,
  FakeV4LocalCity,
  FakeV4Map,
  FakeV4MapTypeId,
  FakeV4Marker,
  FakeV4MenuItem,
  FakeV4Overlay,
  FakeV4Panorama,
  FakeV4PanoramaService,
  FakeV4Pixel,
  FakeV4Point,
  FakeV4PointIconLayer,
  FakeV4PointLayer,
  FakeV4PointShapeLayer,
  FakeV4Polygon,
  FakeV4Polyline,
  FakeV4Prism,
  FakeV4Rectangle,
  FakeV4Size,
  FakeV4TrackLine,
  FakeV4ViewAnimation,
} from './fake-bmap-v4'
export type {
  FakeBMapV4,
  FakeBMapV4Namespace,
  FakeV4AnimationOptions,
  FakeV4Interaction,
  FakeV4JsonpRegistry,
  FakeV4PointLike,
} from './fake-bmap-v4'
